services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: '${APP_NAME:-tg-freispiel}_phpmyadmin'
    hostname: phpmyadmin
    profiles: ['phpmyadmin']
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: '${DB_PORT:-3308}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-nopassword}'
    ports:
      - '${PHPMYADMIN_PORT:-15084}:80'
    networks:
      - internal
      - external
