<?php

declare(strict_types=1);

return [
    'start' => [
        'title' => 'Theatergruppe Freispiel in Dormagen | Proben, Termine & Probestunde',
        'description' => 'Theatergruppe Freispiel aus Dormagen: Entdecke Proben, aktuelle Termine und die Möglichkeit, dich unverbindlich zur nächsten Probestunde anzumelden.',
        'path' => '/',
        'canonical' => '/',
        'nav' => true,
        'nav_label' => 'Home',
        'nav_order' => 10,
        'footer' => true,
        'footer_label' => 'Home',
        'footer_order' => 10,
        'robots' => 'index,follow,max-image-preview:large',
        'og_image' => '/og/start.jpg',
    ],
    'proben' => [
        'title' => 'Proben & Schauspieltraining | Theatergruppe Dormagen',
        'description' => 'Einblicke in Proben, Schauspieltraining und Szenenarbeit der Theatergruppe Freispiel. Jetzt Probestunde in Dormagen entdecken und mitmachen.',
        'path' => '/proben',
        'canonical' => '/proben',
        'nav' => true,
        'nav_label' => 'Proben',
        'nav_order' => 20,
        'footer' => true,
        'footer_label' => 'Proben',
        'footer_order' => 20,
        'robots' => 'index,follow,max-image-preview:large',
        'og_image' => '/og/proben.jpg',
    ],
    'termine' => [
        'title' => 'Termine & Probestunden in Dormagen | Theatergruppe Freispiel',
        'description' => 'Alle aktuellen Termine, Probestunden und Aufführungen der Theatergruppe Freispiel in Dormagen auf einen Blick.',
        'path' => '/termine',
        'canonical' => '/termine',
        'nav' => true,
        'nav_label' => 'Termine',
        'nav_order' => 30,
        'footer' => true,
        'footer_label' => 'Termine',
        'footer_order' => 30,
        'robots' => 'index,follow,max-image-preview:large',
        'og_image' => '/og/termine.jpg',
    ],
    'anmeldung' => [
        'title' => 'Anmeldung zur Probestunde | Theatergruppe Freispiel Dormagen',
        'description' => 'Melde dich unverbindlich zur nächsten Probestunde der Theatergruppe Freispiel in Dormagen an und lerne unser Ensemble kennen.',
        'path' => '/anmeldung',
        'canonical' => '/anmeldung',
        'nav' => true,
        'nav_label' => 'Anmeldung',
        'nav_order' => 40,
        'footer' => true,
        'footer_label' => 'Anmeldung',
        'footer_order' => 40,
        'robots' => 'index,follow,max-image-preview:large',
        'og_image' => '/og/anmeldung.jpg',
    ],
    'kontakt' => [
        'title' => 'Kontakt | Theatergruppe Freispiel in Dormagen',
        'description' => 'Nimm Kontakt zur Theatergruppe Freispiel auf – für Fragen, Aufführungen, Kooperationen oder deine Nachricht an unser Ensemble.',
        'path' => '/kontakt',
        'canonical' => '/kontakt',
        'nav' => true,
        'nav_label' => 'Kontakt',
        'nav_order' => 50,
        'footer' => true,
        'footer_label' => 'Kontakt',
        'footer_order' => 50,
        'robots' => 'index,follow,max-image-preview:large',
        'og_image' => '/og/kontakt.jpg',
    ],
    'datenschutz' => [
        'title' => 'Datenschutzerklärung | Theatergruppe Freispiel',
        'description' => 'Informationen zum Datenschutz und zur Verarbeitung personenbezogener Daten auf der Website der Theatergruppe Freispiel.',
        'path' => '/datenschutz',
        'canonical' => '/datenschutz',
        'nav' => false,
        'footer' => true,
        'footer_label' => 'Datenschutz',
        'footer_order' => 90,
        'robots' => 'noindex,follow',
        'og_image' => '/og/datenschutz.jpg',
    ],
];
